### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by ido-ran** [BrainMaestro/cerebro-stackoverflow#2]
This is amazing plugin you have for Cerebro.
It will be helpful to add keyboard support.

**Comment by BrainMaestro** [comment]
Hey @ido-ran. Thanks. How do you suggest the keyboard support would work?

**Comment by ido-ran** [comment]
I thought on making each entry as only title and short excerpt of the body of the question - this will allow to browse the list with the keyboard and press enter on the entry that looks like the answer which will open the browser.

**Comment by BrainMaestro** [comment]
Interesting. I can't get the body from the initial request though. I'll take a look at it. Thanks for the suggestion

**Comment by BrainMaestro** [comment]
@ido-ran take a look at the keyboard support that was added. Thanks again for the suggestion. It's pretty great.
