### ISSUE TITLE
Fonts look terrible on Linux

### ISSUE THREAD

**Issue by ghost** [BrainMaestro/cerebro-stackoverflow#5]
I like this program, except that the fonts in the results list look fairly dreadful in Linux (or at least on my system: Mint18.1 Cinnamon x64). Is antialiasing, or hinting, enabled? The problem is somewhat exhibited in this screenshot:

![untitled](https://cloud.githubusercontent.com/assets/9998846/23351717/b12a61b4-fcba-11e6-9d65-83dff1b1902a.png)

A bit more configurability - being able to give the search box an outline, a few more themes, being able to remove the translation function - would not go amiss either.

EDIT: Fonts in other applications look alright on my system, though admittedly that was not the case 'out of the box'; I had to install the `Infinality` program and do some other tweaking.

Further edit: I note that the fonts look poor in [this video of Cerebro](https://www.fossmint.com/cerebro-linux-desktop-search-app/), too.

**Comment by BrainMaestro** [comment]
Hey @ACinnamonUserInUK I'll take a look at the font issue. I have run this plugin on a windows and mac but I haven't noticed any font issues. Do you have the font problem with other Cerebro plugins? It might be a problem with Cerebro itself on Linux.

Your other suggestions are great, but I don't control them. You should open an issue in the main Cerebro repo.

Thanks

**Comment by ghost** [comment]
Hello there.

    Yes, the fonts look bad with other Cerebro plugins.

    I am afraid that I have junked Cerebro in favour of ULauncher, which
renders fonts nicely and generally looks gourgeous.

**Comment by BrainMaestro** [comment]
Oh okay. That's sad. It's not an issue with this plugin though, but with the main app. Even though you have stopped using Cerebro, you should probably still report the issue, so it will be fixed. So others can benefit too.

I'll close this now.

**Comment by ghost** [comment]
Ah, my mistake: I thought this was the main Cerebro repo. Could you point me to that please?

**Comment by BrainMaestro** [comment]
---> http://github.com/KELiON/cerebro
